[project]
name = "jev-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=5.0.1",
    "mypy>=2.3.1",
    "pandas>=3.0.6",
    "pandas-stubs>=3.0.5.260914",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
    "scikit-learn>=1.9.1",
    "types-setuptools>=84.0.0.20260812",
]
